import type { ExamQuestion } from '../types';

export const examQuestions: ExamQuestion[] = [
  // EASY LEVEL (Questions 1-10)
  {
    id: 1,
    difficulty: 'easy',
    question: 'Which term describes keeping money in a bank account for future emergencies, a practice generally characterized by high liquidity and lower returns?',
    hint: 'Think about whether the money is being actively used to buy assets or simply being stored.',
    correctAnswer: 'Savings',
    options: [
      {
        text: 'Investment',
        rationale: 'Refers to acquiring assets for capital appreciation (higher risk/return).'
      },
      {
        text: 'Fixed Deposit',
        rationale: 'A type of saving, but not the general practice.'
      },
      {
        text: 'Savings',
        rationale: '✓ Correct. The practice of setting aside excess money, prioritizing high liquidity.'
      },
      {
        text: 'Credit',
        rationale: 'The ability to obtain goods or money now and pay later (opposite of saving).'
      }
    ]
  },
  {
    id: 2,
    difficulty: 'easy',
    question: 'Calculate the simple interest ($I$) earned on a principal ($P$) of RM4,000 at an annual interest rate ($r$) of $3\\%$ for $5$ years ($t$).',
    hint: 'The formula for simple interest is $I = Prt$. Remember to use the rate in decimal form.',
    correctAnswer: 'RM600.00',
    options: [
      {
        text: 'RM120.00',
        rationale: 'Incorrect: Calculates interest for only one year (4,000×0.03×1).'
      },
      {
        text: 'RM200.00',
        rationale: 'Incorrect: Uses a wrong rate or time factor.'
      },
      {
        text: 'RM600.00',
        rationale: '✓ Correct: I=4,000×0.03×5=RM600.'
      },
      {
        text: 'RM60.00',
        rationale: 'Incorrect: Calculation error (dividing by 10 unnecessarily).'
      }
    ]
  },
  {
    id: 3,
    difficulty: 'easy',
    question: 'In the compound interest formula, $MV = P (1 + \\frac{r}{n})^{nt}$, what is the value of $n$ if the interest is compounded quarterly?',
    hint: 'Think about how many times the word \'quarter\' divides a full year.',
    correctAnswer: '4',
    options: [
      {
        text: '1',
        rationale: 'Used for annually.'
      },
      {
        text: '2',
        rationale: 'Used for semi-annually (half-yearly).'
      },
      {
        text: '4',
        rationale: '✓ Correct: Quarterly means 4 times per year.'
      },
      {
        text: '12',
        rationale: 'Used for monthly.'
      }
    ]
  },
  {
    id: 4,
    difficulty: 'easy',
    question: 'Puan Zaleha deposited RM2,500 into a savings account. After 3 years, she earned a total simple interest of RM150. What is her total matured value ($MV$)?',
    hint: 'The total amount of savings is the sum of the initial deposit and the reward given by the bank.',
    correctAnswer: 'RM2,650',
    options: [
      {
        text: 'RM2,350',
        rationale: 'Incorrect: Subtracts the interest.'
      },
      {
        text: 'RM2,500',
        rationale: 'Incorrect: Only the principal amount.'
      },
      {
        text: 'RM2,650',
        rationale: '✓ Correct: MV=P+I=RM2,500+RM150=RM2,650.'
      },
      {
        text: 'RM2,800',
        rationale: 'Incorrect: Calculation error (adding RM300 total).'
      }
    ]
  },
  {
    id: 5,
    difficulty: 'easy',
    question: 'What is the primary source of recurring income generated from an investment in Real Estate (such as buying a shoplot)?',
    hint: 'Think about how a landlord makes money from a property every month.',
    correctAnswer: 'Rental Income',
    options: [
      {
        text: 'Dividends',
        rationale: 'Income from shares/stock ownership.'
      },
      {
        text: 'Capital Gains',
        rationale: 'Profit from selling the property (non-recurring).'
      },
      {
        text: 'Interest',
        rationale: 'Income from bank deposits/bonds.'
      },
      {
        text: 'Rental Income',
        rationale: '✓ Correct: Income generated by allowing others to use the property.'
      }
    ]
  },
  {
    id: 6,
    difficulty: 'easy',
    question: 'Which term best describes an amount of money borrowed that has not yet been repaid?',
    hint: 'This is the opposite of savings; it represents an obligation or liability.',
    correctAnswer: 'Debt',
    options: [
      {
        text: 'Asset',
        rationale: 'Something owned with value.'
      },
      {
        text: 'Credit',
        rationale: 'The ability to obtain funds.'
      },
      {
        text: 'Debt',
        rationale: '✓ Correct: The obligation to repay a sum of money.'
      },
      {
        text: 'Principal',
        rationale: 'The original amount of the loan/deposit.'
      }
    ]
  },
  {
    id: 7,
    difficulty: 'easy',
    question: 'Puan Maryam takes a flat rate personal loan of RM8,000 at $6\\%$ per annum for a period of $4$ years. Calculate the total interest paid for the loan.',
    hint: 'Remember that the total interest for a flat rate loan is calculated over the entire term using the $I = Prt$ formula.',
    correctAnswer: 'RM1,920.00',
    options: [
      {
        text: 'RM480.00',
        rationale: 'Incorrect: Calculates interest for only one year (8,000×0.06×1).'
      },
      {
        text: 'RM1,920.00',
        rationale: '✓ Correct: I=8,000×0.06×4=RM1,920.'
      },
      {
        text: 'RM2,400.00',
        rationale: 'Incorrect: Uses an incorrect rate of 7.5%.'
      },
      {
        text: 'RM9,920.00',
        rationale: 'Incorrect: This is the total repayment amount (P+I).'
      }
    ]
  },
  {
    id: 8,
    difficulty: 'easy',
    question: 'A refrigerator is purchased via a hire purchase loan. The principal loan amount is RM4,500 and the total interest charged is RM300. What is the total amount to be repaid?',
    hint: 'The borrower must pay back the money they borrowed plus the cost charged by the lender.',
    correctAnswer: 'RM4,800',
    options: [
      {
        text: 'RM4,200',
        rationale: 'Incorrect: Subtracts the interest.'
      },
      {
        text: 'RM4,500',
        rationale: 'Incorrect: Only the principal amount.'
      },
      {
        text: 'RM4,800',
        rationale: '✓ Correct: 4,500+300=RM4,800.'
      },
      {
        text: 'RM5,000',
        rationale: 'Incorrect: Calculation error.'
      }
    ]
  },
  {
    id: 9,
    difficulty: 'easy',
    question: 'A flat rate loan requires a total repayment of RM15,000 over a period of $5$ years. Calculate the fixed monthly instalment.',
    hint: 'Remember to convert the loan period from years into the total number of months before dividing the total repayment.',
    correctAnswer: 'RM250.00',
    options: [
      {
        text: 'RM3,000.00',
        rationale: 'Incorrect: This is the annual instalment (15,000÷5).'
      },
      {
        text: 'RM1,250.00',
        rationale: 'Incorrect: This is the instalment if the period was 1 year.'
      },
      {
        text: 'RM250.00',
        rationale: '✓ Correct: Months=5×12=60. RM15,000÷60=RM250.'
      },
      {
        text: 'RM300.00',
        rationale: 'Incorrect: Calculation error.'
      }
    ]
  },
  {
    id: 10,
    difficulty: 'easy',
    question: 'On a credit card statement, which specific failure will result in the immediate imposition of a Late Payment Charge?',
    hint: 'This charge is a penalty for missing the smallest required payment, not the entire debt.',
    correctAnswer: 'Failure to pay the minimum payment amount by the due date.',
    options: [
      {
        text: 'Exceeding the credit limit.',
        rationale: 'Results in an over-limit fee.'
      },
      {
        text: 'Failure to pay the full outstanding balance by the due date.',
        rationale: 'Results in a Finance Charge (interest).'
      },
      {
        text: 'Failure to pay the minimum payment amount by the due date.',
        rationale: '✓ Correct: This triggers the Late Payment Charge penalty.'
      },
      {
        text: 'Making too many cash advance transactions.',
        rationale: 'Results in high interest charges from the transaction date.'
      }
    ]
  },

  // MEDIUM LEVEL (Questions 11-20)
  {
    id: 11,
    difficulty: 'medium',
    question: 'Puan Sofia deposits RM15,000 into a fixed deposit account with an annual interest rate of $4.8\\%$ compounded semi-annually. Calculate the total matured value ($MV$) of her investment after $3$ years. Round your answer to the nearest cent.',
    hint: 'Remember that \'semi-annually\' means the interest is compounded twice a year, so $n=2$ in the compound interest formula.',
    correctAnswer: 'RM17,294.01',
    options: [
      {
        text: 'RM17,160.00',
        rationale: 'Incorrect: Uses simple interest formula.'
      },
      {
        text: 'RM17,294.01',
        rationale: '✓ Correct: MV=15,000(1+0.048/2)^(2×3)≈RM17,294.01.'
      },
      {
        text: 'RM17,351.64',
        rationale: 'Incorrect: Uses monthly compounding (n=12).'
      },
      {
        text: 'RM17,179.92',
        rationale: 'Incorrect: Uses quarterly compounding (n=4).'
      }
    ]
  },
  {
    id: 12,
    difficulty: 'medium',
    question: 'Encik David invested RM10,000 for 2 years. Bank A offers $4\\%$ simple interest, and Bank B offers $4\\%$ interest compounded annually. What is the difference in the total interest earned after 2 years?',
    hint: 'Calculate the total interest for both banks separately ($I_{simple} = Prt$ and $I_{compound} = MV - P$) before finding the difference.',
    correctAnswer: 'RM16.00',
    options: [
      {
        text: 'RM1.60',
        rationale: 'Incorrect: Arithmetic error.'
      },
      {
        text: 'RM4.00',
        rationale: 'Incorrect: Calculation error.'
      },
      {
        text: 'RM16.00',
        rationale: '✓ Correct: I_A=800. MV_B=10,000(1.04)^2=10,816. I_B=816. Difference: 816−800=RM16.00.'
      },
      {
        text: 'RM0.00',
        rationale: 'Incorrect: Compounding must yield more interest over >1 year.'
      }
    ]
  },
  {
    id: 13,
    difficulty: 'medium',
    question: 'Puan Lily bought 5,000 units of Unit Trust at RM1.20 per unit. One year later, she received a dividend distribution of RM300 and sold all the units at RM1.35 per unit. Calculate her Return on Investment (ROI).',
    hint: 'Total Return must include both the profit from selling the units (Capital Gain) and the income received during the year (Dividend).',
    correctAnswer: '17.5%',
    options: [
      {
        text: '12.5%',
        rationale: 'Incorrect: Only considers the capital gain (RM750) and ignores the dividend (RM300).'
      },
      {
        text: '18.5%',
        rationale: 'Incorrect: Calculation error.'
      },
      {
        text: '17.5%',
        rationale: '✓ Correct: ROI=(5,000×0.15)+300/6,000×100%=1,050/6,000×100%=17.5%.'
      },
      {
        text: '22.5%',
        rationale: 'Incorrect: Calculation error.'
      }
    ]
  },
  {
    id: 14,
    difficulty: 'medium',
    question: 'Encik Wong deposited RM9,000 into a Fixed Deposit. After 30 months, he earned a total simple interest of RM900. Calculate the annual interest rate ($r$) offered by the bank.',
    hint: 'First, convert the time from 30 months into years. Then, rearrange the simple interest formula $I = Prt$ to solve for $r$.',
    correctAnswer: '4.00%',
    options: [
      {
        text: '3.33%',
        rationale: 'Incorrect: Result of calculation error.'
      },
      {
        text: '4.00%',
        rationale: '✓ Correct: t=30/12=2.5 years. r=I/(Pt)=900/(9,000×2.5)=0.04 or 4.00%.'
      },
      {
        text: '3.00%',
        rationale: 'Incorrect: Uses t=3 years instead of 2.5 years.'
      },
      {
        text: '10.00%',
        rationale: 'Incorrect: Divides interest by principal only (900/9,000), ignoring t.'
      }
    ]
  },
  {
    id: 15,
    difficulty: 'medium',
    question: 'Mr. Lee deposited RM6,000 into a savings account that offers $3\\%$ interest compounded monthly. Which calculation below correctly shows the accumulated balance after $1 \\text{ year}$?',
    hint: 'Ensure the annual rate is divided by the compounding frequency, and the time in the power is multiplied by the compounding frequency.',
    correctAnswer: 'RM6,000×(1+0.03/12)^(12×1)',
    options: [
      {
        text: 'RM6,000×(1+0.03)^1',
        rationale: 'Incorrect: Simple interest formula.'
      },
      {
        text: 'RM6,000×(1+0.003)^12',
        rationale: 'Incorrect: Uses a wrong rate in the base.'
      },
      {
        text: 'RM6,000×(1+0.03/12)^(12×1)',
        rationale: '✓ Correct: Matches the formula MV=P(1+r/n)^nt with P=6,000,r=0.03,n=12,t=1.'
      },
      {
        text: 'RM6,000+(RM6,000×0.03×12)',
        rationale: 'Incorrect: Simple interest formula with incorrect time conversion.'
      }
    ]
  },
  {
    id: 16,
    difficulty: 'medium',
    question: 'Puan Aisha takes a flat rate hire purchase loan for RM40,000 at an annual interest rate of $5.5\\%$. The loan period is $48$ months. Calculate Puan Aisha\'s fixed monthly instalment.',
    hint: 'First, convert $48$ months to years ($t=4$). Then, calculate the total interest, total repayment, and finally the monthly instalment.',
    correctAnswer: 'RM1,016.67',
    options: [
      {
        text: 'RM933.33',
        rationale: 'Incorrect: Divides only the principal by 48 months.'
      },
      {
        text: 'RM1,180.00',
        rationale: 'Incorrect: Based on 36 months (3 years).'
      },
      {
        text: 'RM1,093.33',
        rationale: 'Incorrect: Calculation error.'
      },
      {
        text: 'RM1,016.67',
        rationale: '✓ Correct: I=40,000×0.055×4=8,800. Repayment=48,800. 48,800÷48≈RM1,016.67.'
      }
    ]
  },
  {
    id: 17,
    difficulty: 'medium',
    question: 'A refrigerator is purchased on a hire purchase scheme. The monthly instalment is RM250, and the loan period is 2 years. If the total interest paid is RM600, calculate the original principal loan amount.',
    hint: 'First, find the total amount repaid over 2 years, then subtract the total interest to find the principal.',
    correctAnswer: 'RM5,400',
    options: [
      {
        text: 'RM5,400',
        rationale: '✓ Correct: Total Repayment=250×24=6,000. P=6,000−600=RM5,400.'
      },
      {
        text: 'RM6,000',
        rationale: 'Incorrect: This is the total repayment, which includes the interest.'
      },
      {
        text: 'RM4,800',
        rationale: 'Incorrect: Calculation error.'
      },
      {
        text: 'RM7,200',
        rationale: 'Incorrect: Uses a 3-year term (36 months).'
      }
    ]
  },
  {
    id: 18,
    difficulty: 'medium',
    question: 'Encik Tan had an outstanding credit card balance of RM2,800. The annual interest rate (finance charge) is $15\\%$. Calculate the finance charge applied to his account for that month, assuming the charge is applied on the outstanding balance.',
    hint: 'The finance charge for one month is calculated using the monthly interest rate, which is the annual rate divided by $12$.',
    correctAnswer: 'RM35.00',
    options: [
      {
        text: 'RM420.00',
        rationale: 'Incorrect: This is the annual finance charge.'
      },
      {
        text: 'RM35.00',
        rationale: '✓ Correct: Monthly Rate=15%÷12=1.25%. Charge=2,800×0.0125=RM35.00.'
      },
      {
        text: 'RM233.33',
        rationale: 'Incorrect: Calculation error.'
      },
      {
        text: 'RM42.00',
        rationale: 'Incorrect: Result of using an 18% annual rate.'
      }
    ]
  },
  {
    id: 19,
    difficulty: 'medium',
    question: 'Why is the total interest paid on a flat rate hire purchase loan usually higher than the total interest paid on a housing loan of the same principal, rate, and time?',
    hint: 'Think about what amount the interest percentage is applied to each year for both types of loans.',
    correctAnswer: 'Because flat rate interest is calculated on the original principal throughout the entire term, while the housing loan interest is calculated on the remaining reducing balance.',
    options: [
      {
        text: 'The flat rate loan allows for more predictable monthly budgeting.',
        rationale: 'This is a side benefit, not the core financial reason for higher cost.'
      },
      {
        text: 'Because flat rate interest is calculated on the original principal throughout the entire term, while the housing loan interest is calculated on the remaining reducing balance.',
        rationale: '✓ Correct: The constant principal means interest is always maximized, leading to a higher total cost.'
      },
      {
        text: 'Because the loan term for hire purchase is much shorter than the term for a housing loan.',
        rationale: 'A shorter term usually means less total interest.'
      },
      {
        text: 'Because the flat rate loan is compounded more frequently (e.g., monthly) than the housing loan.',
        rationale: 'Flat rate interest is fixed and not subject to the compounding frequency in the same way.'
      }
    ]
  },
  {
    id: 20,
    difficulty: 'medium',
    question: 'Encik Ali\'s loan has a total repayment amount of RM24,000 over 4 years. If the annual flat interest rate is $8\\%$, calculate the original principal amount ($P$) of the loan.',
    hint: 'Use the formula $\\text{Total Repayment} = P(1 + rt)$. Substitute the known values and rearrange the equation to solve for $P$.',
    correctAnswer: 'RM18,181.82',
    options: [
      {
        text: 'RM20,000',
        rationale: 'Incorrect: Calculation error.'
      },
      {
        text: 'RM18,181.82',
        rationale: '✓ Correct: 24,000=P(1+0.08×4)=P(1.32). P=24,000÷1.32≈RM18,181.82.'
      },
      {
        text: 'RM19,200',
        rationale: 'Incorrect: Result of calculation error.'
      },
      {
        text: 'RM21,000',
        rationale: 'Incorrect: Result of calculation error.'
      }
    ]
  },

  // HARD LEVEL (Questions 21-30)
  {
    id: 21,
    difficulty: 'hard',
    question: 'Puan Maimunah aims to have a total Matured Value ($MV$) of RM12,000 in her savings account after 5 years. If the bank offers an annual interest rate of $4\\%$ compounded monthly, what is the minimum initial Principal ($P$) she must deposit today? Round your answer to the nearest RM10.',
    hint: 'You need to rearrange the compound interest formula to solve for the initial Principal, $P$. Remember that $P = MV \\div (1 + \\frac{r}{n})^{nt}$.',
    correctAnswer: 'RM9,830',
    options: [
      {
        text: 'RM9,820',
        rationale: 'Incorrect: Result of calculation error.'
      },
      {
        text: 'RM9,830',
        rationale: '✓ Correct: P=12,000÷(1+0.04/12)^60≈RM9,834.74, which rounds to RM9,830.'
      },
      {
        text: 'RM10,000',
        rationale: 'Incorrect: Ignores the benefit of the compounded interest.'
      },
      {
        text: 'RM11,538',
        rationale: 'Incorrect: Result of calculating simple interest instead of compound interest.'
      }
    ]
  },
  {
    id: 22,
    difficulty: 'hard',
    question: 'Encik Fazli has RM20,000 to invest for 4 years. He has two options: Bank X offers $3.8\\%$ compounded monthly, and Bank Y offers $3.9\\%$ compounded semi-annually. What is the difference in the Matured Value ($MV$) between the two options after 4 years?',
    hint: 'Calculate the final $MV$ for Bank X ($n=12$) and Bank Y ($n=2$) separately using the compound interest formula before finding the difference.',
    correctAnswer: 'RM10.35',
    options: [
      {
        text: 'RM10.35',
        rationale: '✓ Correct: MV_X≈RM23,371.49. MV_Y≈RM23,361.14. Difference: RM10.35.'
      },
      {
        text: 'RM5.25',
        rationale: 'Incorrect: Calculation error.'
      },
      {
        text: 'RM51.01',
        rationale: 'Incorrect: Calculation error.'
      },
      {
        text: 'RM30.50',
        rationale: 'Incorrect: Result of using a higher rate for Bank Y.'
      }
    ]
  },
  {
    id: 23,
    difficulty: 'hard',
    question: 'An investor bought 1,000 shares at RM3.00 per share. Later, the company issued a 2-for-1 bonus share split, doubling his shares but halving the price. He then received RM400 in dividends and sold all shares at RM1.80 per share. Calculate his Return on Investment (ROI).',
    hint: 'The bonus split does not change the total capital value immediately, but it changes the number of shares (to $2,000$) and the per-share price (to $RM1.50$ theoretical average).',
    correctAnswer: '33.3%',
    options: [
      {
        text: '26.7%',
        rationale: 'Incorrect: Calculation error in determining the total return.'
      },
      {
        text: '33.3%',
        rationale: '✓ Correct: Initial=3,000. Sold Value=2,000×1.80=3,600. Total Return=(3,600−3,000)+400=1,000. ROI=1,000/3,000≈33.3%.'
      },
      {
        text: '6.7%',
        rationale: 'Incorrect: Only considers the dividend as a return.'
      },
      {
        text: '60.0%',
        rationale: 'Incorrect: Compares the final sales value to the initial investment (3,600/3,000), ignoring the dividend.'
      }
    ]
  },
  {
    id: 24,
    difficulty: 'hard',
    question: 'Encik Hassan deposited RM5,000 into an account offering $5\\%$ annual interest compounded annually. He needs to withdraw his savings the moment the value reaches RM6,200. Using the formula $t = \\frac{\\log (MV/P)}{\\log (1+r)}$, determine the approximate number of years needed.',
    hint: 'Even if the calculated time is fractional, remember that interest is only calculated and added at the end of the full compounding period (annually).',
    correctAnswer: '5 years',
    options: [
      {
        text: '4 years',
        rationale: 'Incorrect: The actual time is 4.4 years, meaning the 4th year payment is not enough.'
      },
      {
        text: '5 years',
        rationale: '✓ Correct: Calculation yields t≈4.40 years. Since compounding is annual, the MV reaches RM6,381.41 only after the 5th year\'s calculation.'
      },
      {
        text: '6 years',
        rationale: 'Incorrect: The target is already exceeded at the end of year 5.'
      },
      {
        text: '4.4 years',
        rationale: 'Incorrect: This is the exact value, but it must be rounded up to the next compounding period.'
      }
    ]
  },
  {
    id: 25,
    difficulty: 'hard',
    question: 'Which of the following describes the investment option with the highest Effective Annual Rate (EAR), given a nominal annual rate of $6\\%$?',
    hint: 'The Effective Annual Rate (EAR) formula shows that the value increases as the compounding frequency ($n$) increases, making monthly compounding the most beneficial.',
    correctAnswer: 'Compounded Monthly (EAR=6.168%)',
    options: [
      {
        text: 'Compounded Annually (EAR=6.00%)',
        rationale: 'EAR is lowest when n is lowest.'
      },
      {
        text: 'Compounded Semi-annually (EAR=6.09%)',
        rationale: 'EAR is higher than annual, but lower than quarterly/monthly.'
      },
      {
        text: 'Compounded Quarterly (EAR=6.136%)',
        rationale: 'EAR is higher than semi-annual, but lower than monthly.'
      },
      {
        text: 'Compounded Monthly (EAR=6.168%)',
        rationale: '✓ Correct: Highest compounding frequency (n=12) gives the highest EAR.'
      }
    ]
  },
  {
    id: 26,
    difficulty: 'hard',
    question: 'A loan of RM50,000 is repaid with a fixed monthly instalment of RM1,150 over 4 years. Calculate the annual flat interest rate ($r$) charged on this loan. Round to two decimal places.',
    hint: 'First, calculate the total repayment and total interest. Then, rearrange the $I = Prt$ formula to solve for the rate $r$: $r = \\frac{I}{Pt}$.',
    correctAnswer: '2.60%',
    options: [
      {
        text: '7.50%',
        rationale: 'Incorrect: Calculation error.'
      },
      {
        text: '2.60%',
        rationale: '✓ Correct: Total Interest=(1,150×48)−50,000=5,200. r=5,200/(50,000×4)=0.026 or 2.60%.'
      },
      {
        text: '5.00%',
        rationale: 'Incorrect: Result of calculation error.'
      },
      {
        text: '10.40%',
        rationale: 'Incorrect: Ignores the time factor t=4 years.'
      }
    ]
  },
  {
    id: 27,
    difficulty: 'hard',
    question: 'Which of the following statements provides the most accurate financial reason why a reducing balance loan (like a housing loan) is preferable to a flat rate loan (like a car loan) for a long-term debt?',
    hint: 'Consider the core principle of interest calculation: what amount is the interest percentage applied to throughout the life of the loan?',
    correctAnswer: 'The total amount of interest paid on the reducing balance loan decreases over time, resulting in a significantly lower overall cost.',
    options: [
      {
        text: 'The flat rate loan allows for more predictable monthly budgeting.',
        rationale: 'This is a side benefit, not the core financial cost reason.'
      },
      {
        text: 'The reducing balance loan has a shorter loan term than the flat rate loan.',
        rationale: 'Loan term is independent of the interest calculation method.'
      },
      {
        text: 'The total amount of interest paid on the reducing balance loan decreases over time, resulting in a significantly lower overall cost.',
        rationale: '✓ Correct: Interest is constantly recalculated on a smaller remaining principal.'
      },
      {
        text: 'The reducing balance loan avoids any late payment charges, unlike the flat rate loan.',
        rationale: 'All loans penalize late payments.'
      }
    ]
  },
  {
    id: 28,
    difficulty: 'hard',
    question: 'Mr. Siva\'s credit card statement has a balance of RM5,000 (due January 20). The minimum payment is $5\\%$ of the balance or RM50, whichever is higher. He made no payment. The bank charges a monthly interest of $1.5\\%$ and a late fee of RM50. Calculate his new outstanding balance for the February statement.',
    hint: 'Remember that if no payment is made, the new balance must include the interest on the original balance (Finance Charge) AND the penalty (Late Payment Charge).',
    correctAnswer: 'RM5,125.00',
    options: [
      {
        text: 'RM5,075.00',
        rationale: 'Incorrect: Only includes the Finance Charge (RM75.00).'
      },
      {
        text: 'RM5,125.00',
        rationale: '✓ Correct: FC=5,000×0.015=75. New Balance=5,000+75(FC)+50(LPF)=RM5,125.00.'
      },
      {
        text: 'RM4,750.00',
        rationale: 'Incorrect: Calculation error.'
      },
      {
        text: 'RM5,095.00',
        rationale: 'Incorrect: Calculation error.'
      }
    ]
  },
  {
    id: 29,
    difficulty: 'hard',
    question: 'Puan Liza wants to take a personal loan of RM30,000 for 5 years. She can only afford a monthly instalment of RM650. What is the maximum annual flat interest rate ($r$) the bank can offer her for her to afford the loan?',
    hint: 'First, calculate the total affordable repayment ($RM650 \\times 60 \\text{ months}$). Then, find the total interest and solve for $r$ using the inverse $I = Prt$ formula.',
    correctAnswer: '6.0%',
    options: [
      {
        text: '5.5%',
        rationale: 'Incorrect: This is the rate if she could afford RM637.50 monthly.'
      },
      {
        text: '6.0%',
        rationale: '✓ Correct: Total Repayment=650×60=39,000. Total Interest=9,000. r=9,000/(30,000×5)=0.06 or 6.0%.'
      },
      {
        text: '7.2%',
        rationale: 'Incorrect: This rate would result in an unaffordable monthly instalment of RM680.'
      },
      {
        text: '4.5%',
        rationale: 'Incorrect: This is the rate if she could afford RM612.50 monthly.'
      }
    ]
  },
  {
    id: 30,
    difficulty: 'hard',
    question: 'Why is it mathematically impossible to use the simple interest formula ($I = Prt$) to accurately model the interest growth for an investment compounded monthly over a period of 10 years?',
    hint: 'Recall the fundamental difference in the definition of simple interest versus compound interest, focusing on which amount the interest is applied to.',
    correctAnswer: 'The simple interest formula only calculates interest on the initial principal, ignoring the accumulation of interest on previously earned interest.',
    options: [
      {
        text: 'The simple interest formula cannot handle periods longer than one year, unlike the compound interest formula.',
        rationale: 'Incorrect: I=Prt can handle any t.'
      },
      {
        text: 'The variable r in the simple interest formula is always a whole number, whereas compound interest requires a decimal rate.',
        rationale: 'Incorrect: r must be decimal in both formulas.'
      },
      {
        text: 'The simple interest formula only calculates interest on the initial principal, ignoring the accumulation of interest on previously earned interest.',
        rationale: '✓ Correct: The failure to adjust the principal is the fundamental mathematical difference.'
      },
      {
        text: 'The simple interest formula cannot include the compounding frequency (n) of the investment, making the calculation inaccurate.',
        rationale: 'Incorrect: This is true, but the core issue is the accumulation of the interest itself.'
      }
    ]
  }
];
